python -m unittest unittest_issue_03.py
.F..
======================================================================
FAIL: test_al1 (unittest_issue_03.TestFitTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Дмитрий\unittest_issue_03.py", line 53, in test_al1
    self.assertEqual(actual, expected)
AssertionError: Lists differ: [('A', [0, 0, 1]), ('B', [0, 1, 0]), ('C', [1, 0, 0])] != [('A', [1, 0, 0]), ('B', [0, 1, 0]), ('C', [0, 0, 1])]

First differing element 0:
('A', [0, 0, 1])
('A', [1, 0, 0])

- [('A', [0, 0, 1]), ('B', [0, 1, 0]), ('C', [1, 0, 0])]
?             ---                             ---

+ [('A', [1, 0, 0]), ('B', [0, 1, 0]), ('C', [0, 0, 1])]
?         +++                                     +++


----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=1)